language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: g2a02SpRB5zQOo1QV7R5zO8sX2vF5+97MAOFQN1BeQZfV6vkIG+j0anKNydiRqo8pRrAli21EXMXGJ5kmqnnx6NiTEA+4kdCddp13jYO9G4ampI65nKHL767tagt6fY/OWhLSnzFUtdmbWpjIYL5jaIHshPhOWu3KmMuEs/ogk1e6xCsUXBivz1d2ve/4tH4uJrcHycLlp+xhdj8NR7lYyfXqRICD4RHSgYELC9ZQfqeD9lCn4v0By6nfkn4U8xo2rh6C9xh+/obRoqoKmYes7hyLuP9SD5tRRzqWeILhiXfeDfpfvfZIzHuqlUX/k5CjwuxTHKUg6+sbqX/yIToJwNu4EyQZ7l/NtR+xAZbG38RVuLH0tsXO1hQpdxOchgLYNbvFe2JviLGSnuEf09E7+Lv4VPdPsbXjTJdk5U31nuWTlkDn+CeM1zPEfKJDvjqLPKF7kXISBT4pGcT7kGPg1oyylbKtViMnm7LhyUWYtGw8+XywAONb6jM5Lcih87IBdZtHtpdhbhSF95T3EC7817eJ3NeTSjBfslE3o7CUVXSQ5plWjU2Edq3+z15gOhY2/pcXxzBTcmaX8OUNdnX0FwnWCjFQXf1TT93sXgMbxwV7k1y6u4nrrzN8m8h+il0d16EBY5w9n3QqApykHGCv8jkcINdU8GfCpT1sYSeuLE=
  app: murmuring-brushlands-65684
  on:
    repo: Vlacross/intergration-testing
